[package]
name = "hello"
version = "0.1.0"
authors = ["andy-thomason <andy@andythomason.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
extendr-api = {path = "../../../../extendr-api"}

[workspace]
